"""
Neo4j Cypher Compiler.

Generates Cypher DDL statements to create the ontology schema
in Neo4j, including node labels, relationship types, constraints,
and indexes.
"""
from __future__ import annotations
from ..models import Ontology


def compile_neo4j(ontology: Ontology) -> str:
    """Compile ontology to Neo4j Cypher statements."""
    lines: list[str] = []
    name = ontology.manifest.name if ontology.manifest else "ontology"

    lines.append(f"// ==============================================")
    lines.append(f"// Lore → Neo4j Schema: {name}")
    lines.append(f"// Generated by `lore compile --target neo4j`")
    lines.append(f"// ==============================================")
    lines.append("")

    # Node constraints and indexes
    lines.append("// --- Node Constraints ---")
    lines.append("")

    for entity in ontology.entities:
        label = entity.name

        # Provenance comment
        if entity.provenance or entity.status:
            prov_parts = []
            if entity.status:
                prov_parts.append(f"status={entity.status}")
            if entity.provenance:
                if entity.provenance.source:
                    prov_parts.append(f"source={entity.provenance.source}")
                if entity.provenance.confidence is not None:
                    prov_parts.append(f"confidence={entity.provenance.confidence}")
            if prov_parts:
                lines.append(f"// {label}: {', '.join(prov_parts)}")

        # Find unique attributes for constraints
        unique_attrs = [a for a in entity.attributes if "unique" in a.constraints]
        required_attrs = [a for a in entity.attributes if "required" in a.constraints]

        for attr in unique_attrs:
            lines.append(
                f"CREATE CONSTRAINT {label.lower()}_{attr.name}_unique "
                f"IF NOT EXISTS FOR (n:{label}) REQUIRE n.{attr.name} IS UNIQUE;"
            )

        for attr in required_attrs:
            lines.append(
                f"CREATE CONSTRAINT {label.lower()}_{attr.name}_exists "
                f"IF NOT EXISTS FOR (n:{label}) REQUIRE n.{attr.name} IS NOT NULL;"
            )

        lines.append("")

    # Indexes for common query patterns
    lines.append("// --- Indexes ---")
    lines.append("")

    for entity in ontology.entities:
        label = entity.name
        # Index enum and reference attributes (commonly queried)
        for attr in entity.attributes:
            if attr.type.startswith("enum") or attr.type == "reference":
                lines.append(
                    f"CREATE INDEX {label.lower()}_{attr.name}_idx "
                    f"IF NOT EXISTS FOR (n:{label}) ON (n.{attr.name});"
                )

    lines.append("")

    # Relationship type documentation
    lines.append("// --- Relationship Types ---")
    lines.append("// Neo4j doesn't require DDL for relationships,")
    lines.append("// but these are the defined types for reference:")
    lines.append("")

    for rel in ontology.all_relationships:
        props = ""
        if rel.properties:
            prop_list = ", ".join(f"{p.name}: {p.type}" for p in rel.properties)
            props = f" {{{prop_list}}}"
        lines.append(
            f"// (:{rel.from_entity})-[:{rel.name}{props}]->(:{rel.to_entity})  "
            f"// {rel.cardinality}"
        )

    lines.append("")

    # Example queries from traversals
    lines.append("// --- Named Traversal Queries ---")
    lines.append("")

    for trav in ontology.all_traversals:
        lines.append(f"// Traversal: {trav.name}")
        lines.append(f"// {trav.description}")

        # Convert traversal path to Cypher pattern
        cypher = _traversal_to_cypher(trav.path)
        if cypher:
            lines.append(f"// {cypher}")
        lines.append("")

    return "\n".join(lines)


def _traversal_to_cypher(path: str) -> str:
    """Best-effort conversion of traversal path to Cypher MATCH pattern."""
    import re

    # Simple pattern: Entity -[REL]-> Entity -[REL]-> Entity
    parts = re.split(r'\s*-\[', path)
    if len(parts) < 2:
        return f"// Raw path: {path}"

    cypher_parts = []
    first_entity = parts[0].strip().rstrip("<").strip()
    cypher_parts.append(f"(a:{first_entity})")

    for part in parts[1:]:
        match = re.match(r'(\w+(?:\s*=\s*\w+)?)\](-|<)?>\s*(\w+)(?:\s*\((.+)\))?', part)
        if match:
            rel_name = match.group(1).strip()
            direction = match.group(2) or ""
            target = match.group(3).strip()
            modifier = match.group(4) or ""

            if "=" in rel_name:
                # Filter expression like type = expansion
                rel_name_clean, _, filter_val = rel_name.partition("=")
                cypher_parts.append(f"-[:{rel_name_clean.strip()} {{{rel_name_clean.strip()}: '{filter_val.strip()}'}}]->({target.lower()}:{target})")
            else:
                cypher_parts.append(f"-[:{rel_name}]->({target.lower()}:{target})")

    if cypher_parts:
        return "MATCH " + "".join(cypher_parts) + " RETURN *"

    return f"// Raw path: {path}"
